import { useEffect, useRef, useState } from 'react';
import type { PptPage, PptProject } from '../../shared/types/ipc';
import { useToast } from '../../shared/ui';

export function PptPageEditTools({ project, page, onRefresh, onDirtyChange }: { project: PptProject; page: PptPage; onRefresh: () => Promise<unknown>; onDirtyChange?: (value: boolean) => void }) {
  const api = window.yibiao!.ppt, { showToast } = useToast();
  const [elements, setElements] = useState<Array<{ elementId: string; type: string; text: string; attributes: Record<string, string> }>>([]), [target, setTarget] = useState('');
  const [fill, setFill] = useState(''), [size, setSize] = useState(''), [dx, setDx] = useState('0'), [dy, setDy] = useState('0');
  const [chartId, setChartId] = useState(''), [categories, setCategories] = useState(''), [series, setSeries] = useState('');
  const [charts, setCharts] = useState<Array<{ elementId: string; name: string }>>([]);
  const [annotation, setAnnotation] = useState(''), [annotations, setAnnotations] = useState<Awaited<ReturnType<typeof api.annotations>>>([]), [selected, setSelected] = useState<string[]>([]);
  const [busy, setBusy] = useState(false);
  const [notes, setNotes] = useState(''), [notesDirty, setNotesDirty] = useState(false);
  const draft = useRef({ key: '', text: '', dirty: false });
  const running = project.jobs.some((job) => ['running', 'queued'].includes(job.status));
  async function run(action: () => Promise<unknown>) { setBusy(true); try { await action(); await onRefresh(); setAnnotations(await api.annotations({ projectId: project.projectId })); } catch (error) { showToast(String(error), 'error'); } finally { setBusy(false); } }
  useEffect(() => {
    let live = true; setTarget(''); setChartId(''); setSelected([]);
    void api.notes({ projectId: project.projectId, slideId: page.slideId }).then((value) => { if (live) { const key = `${project.projectId}:${page.slideId}`; if (draft.current.key === key && draft.current.dirty && draft.current.text !== value) return; draft.current = { key, text: value, dirty: false }; setNotes(value); setNotesDirty(false); onDirtyChange?.(false); } }).catch((error) => showToast(String(error), 'error'));
    void Promise.all([api.page({ projectId: project.projectId, slideId: page.slideId }), api.annotations({ projectId: project.projectId })]).then(([value, notes]) => { if (live) { setElements(value.elements); setAnnotations(notes); } }).catch((error) => showToast(String(error), 'error'));
    if (project.route === 'edit-native') void api.nativeObjects({ projectId: project.projectId }).then((value) => { if (live) setCharts(value.pages.find((item) => item.slideId === page.slideId)?.elements.filter((item) => item.chart) || []); }).catch((error) => showToast(String(error), 'error'));
    return () => { live = false; };
  }, [project.projectId, project.revision, page.slideId]);
  return <details className="ppt-direct-edit"><summary>元素、图表与批注</summary>
    <fieldset disabled={running || busy}><label>页面元素<select aria-label="页面元素" value={target} onChange={(event) => { setTarget(event.target.value); const item = elements.find((item) => item.elementId === event.target.value); setFill(item?.attributes.fill || ''); setSize(item?.attributes['font-size'] || ''); }}><option value="">选择元素</option>{elements.map((item) => <option key={item.elementId} value={item.elementId}>{item.elementId} · {item.text.slice(0, 30) || item.type}</option>)}</select></label>
      <div className="ppt-actions"><label>颜色<input value={fill} onChange={(event) => setFill(event.target.value)} placeholder="#336699" /></label><label>字号<input type="number" min="8" max="200" value={size} onChange={(event) => setSize(event.target.value)} /></label><label>横向移动(px)<input type="number" value={dx} onChange={(event) => setDx(event.target.value)} /></label><label>纵向移动(px)<input type="number" value={dy} onChange={(event) => setDy(event.target.value)} /></label>
      <button disabled={!target} onClick={() => void run(() => api.edit({ projectId: project.projectId, revision: project.revision, slideId: page.slideId, elementId: target, attributes: { ...(fill ? { fill } : {}), ...(size ? { 'font-size': size } : {}), ...(Number(dx) || Number(dy) ? { transform: `${elements.find((item) => item.elementId === target)?.attributes.transform || ''} translate(${Number(dx) || 0} ${Number(dy) || 0})` } : {}) } }))}>应用元素修改</button></div>
      {project.route === 'edit-native' && <details><summary>替换原生图表数据</summary><p>选择已映射的图表对象ID；类别逐行填写，系列填写带名称和数值数组的JSON。共享或复杂工作簿会阻止修改。</p><label>当前页图表<select value={chartId} onChange={(event) => setChartId(event.target.value)}><option value="">选择已映射图表</option>{charts.map((item) => <option key={item.elementId} value={item.elementId}>{item.name}</option>)}</select></label><label>类别<textarea value={categories} onChange={(event) => setCategories(event.target.value)} /></label><label>系列数据<textarea value={series} onChange={(event) => setSeries(event.target.value)} placeholder={'[{"name":"销售","values":[12,34]}]'} /></label><button disabled={!chartId || !categories.trim() || !series.trim()} onClick={() => void run(() => api.nativeReplace({ projectId: project.projectId, revision: project.revision, chart: { page: (page.sourceSlide || page.position + 1) - 1, slideId: page.slideId, elementId: chartId, categories: categories.split('\n').map((item) => item.trim()).filter(Boolean), series: JSON.parse(series) } }))}>应用图表数据</button></details>}
      <label>当前页批注<textarea value={annotation} onChange={(event) => setAnnotation(event.target.value)} placeholder="说明要修改的内容；可绑定上面选定元素" /></label><button disabled={!annotation.trim()} onClick={() => void run(async () => { await api.saveAnnotation({ projectId: project.projectId, revision: project.revision, slideId: page.slideId, elementId: target || undefined, instruction: annotation }); setAnnotation(''); })}>保存批注</button>
      {annotations.filter((item) => item.slideId === page.slideId).map((item) => <label key={item.annotationId}><input type="checkbox" disabled={Boolean(item.appliedAt) || item.sourceHash !== page.hash} checked={selected.includes(item.annotationId)} onChange={(event) => setSelected(event.target.checked ? [...selected, item.annotationId] : selected.filter((id) => id !== item.annotationId))} />{item.instruction} · {item.appliedAt ? '已应用' : item.sourceHash !== page.hash ? '页面变化，需重新保存' : '待应用'}</label>)}
      <button disabled={!selected.length || project.confirmedRevision !== project.revision} onClick={() => void run(() => api.applyAnnotations({ projectId: project.projectId, revision: project.revision, annotationIds: selected }))}>让 Agent 应用所选批注</button>
      <details><summary>逐页讲稿 {notesDirty ? '· 未保存' : ''}</summary><textarea aria-label="当前页讲稿" value={notes} onChange={(event) => { draft.current = { key: `${project.projectId}:${page.slideId}`, text: event.target.value, dirty: true }; setNotes(event.target.value); setNotesDirty(true); onDirtyChange?.(true); }} /><button disabled={!notesDirty} onClick={() => void run(() => api.saveNotes({ projectId: project.projectId, revision: project.revision, slideId: page.slideId, content: notes }))}>保存本页讲稿</button><button disabled={!notesDirty} onClick={() => void run(async () => { const value = await api.notes({ projectId: project.projectId, slideId: page.slideId }); draft.current = { key: `${project.projectId}:${page.slideId}`, text: value, dirty: false }; setNotes(value); setNotesDirty(false); onDirtyChange?.(false); })}>取消讲稿修改</button></details>
    </fieldset>
  </details>;
}
