import * as Dialog from '@radix-ui/react-dialog';
import { useEffect, useState } from 'react';
import type { PptSkill } from '../../shared/types/ipc';
import { useToast } from '../../shared/ui';

export function PptSkillPanel({ open, onOpenChange }: { open: boolean; onOpenChange: (value: boolean) => void }) {
  const { showToast } = useToast();
  const [items, setItems] = useState<PptSkill[]>([]), [url, setUrl] = useState('');
  const [candidate, setCandidate] = useState<{ candidateId?: string; candidates: PptSkill[] } | null>(null);
  const [selected, setSelected] = useState<string[]>([]), [request, setRequest] = useState<{ requestId: string; status: string } | null>(null);
  const [normalizePath, setNormalizePath] = useState(''), [name, setName] = useState(''), [description, setDescription] = useState('');
  const [remove, setRemove] = useState<PptSkill[] | null>(null), [busy, setBusy] = useState(false), [checked, setChecked] = useState<string[]>([]), [removeReferenced, setRemoveReferenced] = useState(false);
  const [storage, setStorage] = useState<Awaited<ReturnType<NonNullable<Window['yibiao']>['ppt']['skills']['storage']>> | null>(null);
  const [directory, setDirectory] = useState(''), [system, setSystem] = useState(false), [acceptedSystem, setAcceptedSystem] = useState(false);
  async function run(action: () => Promise<unknown>) { setBusy(true); try { await action(); setItems(await window.yibiao!.ppt.skills.list()); setStorage(await window.yibiao!.ppt.skills.storage()); } catch (error) { showToast(String(error), 'error'); } finally { setBusy(false); } }
  async function discard() { if (candidate?.candidateId) await window.yibiao!.ppt.skills.discard({ candidateId: candidate.candidateId }); setCandidate(null); }
  useEffect(() => { if (open) void run(async () => {}); }, [open]);
  async function identifyPath(path: string) {
    await discard();
    const value = await window.yibiao!.ppt.skills.identify({ path });
    if (value.needsNormalization) setNormalizePath(value.originalPath || path);
    else { setCandidate(value); setSelected(value.candidates.filter((item) => !item.missing?.length).map((item) => item.contentHash)); }
  }
  async function identify(kind: 'folder' | 'file' | 'zip') { const path = await window.yibiao!.ppt.selectSkill(kind); if (path) await identifyPath(path); }
  return <Dialog.Root open={open} onOpenChange={(value) => { if (!busy) { if (!value) void run(discard); onOpenChange(value); } }}><Dialog.Portal><Dialog.Overlay className="resource-preview-overlay" /><Dialog.Content className="ppt-skill-dialog">
    <header><Dialog.Title>技能管理</Dialog.Title><Dialog.Close disabled={busy} aria-label="关闭技能管理">×</Dialog.Close></header>
    <Dialog.Description>安装、启用和兼容状态分别记录。第三方脚本不会自动执行，项目锁定版本不会随更新被覆盖。</Dialog.Description>
    <details><summary>技能位置与空间</summary><p>{storage?.root}<br />版本副本 {((storage?.bytes || 0) / 1024 ** 2).toFixed(1)} MB；迁移后原副本保留。</p><button disabled={busy || Boolean(candidate)} onClick={() => void run(async () => { const value = await window.yibiao!.ppt.selectDirectory(); if (value) { setDirectory(value.path); setSystem(value.systemVolume); setAcceptedSystem(!value.systemVolume); } })}>选择迁移父目录</button>{directory && <p>{directory}</p>}{directory && system && !acceptedSystem && <section className="ppt-confirm-card"><strong>所选目录在系统盘</strong><p>技能和安装候选可能占用较多空间，建议重新选择。</p><button onClick={() => setDirectory('')}>重新选择（推荐）</button><button onClick={() => setAcceptedSystem(true)}>仍然使用</button></section>}{directory && <button disabled={busy || !acceptedSystem} onClick={() => void run(async () => { await window.yibiao!.ppt.skills.configure({ parent: directory, confirmed: true }); setDirectory(''); })}>确认复制、校验并迁移</button>}</details>
    <div className="ppt-actions" onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); const file = event.dataTransfer.files[0]; if (file) void run(() => identifyPath(window.yibiao!.ppt.droppedPath(file))); }}><button disabled={busy} onClick={() => void run(() => identify('file'))}>技能文件</button><button disabled={busy} onClick={() => void run(() => identify('folder'))}>完整文件夹</button><button disabled={busy} onClick={() => void run(() => identify('zip'))}>ZIP 技能包</button><span>也可拖入文件或文件夹</span></div>
    <div className="ppt-actions"><input aria-label="GitHub 技能地址" value={url} onChange={(event) => setUrl(event.target.value)} placeholder="GitHub 仓库或技能子目录地址" /><button disabled={busy || !url.trim()} onClick={() => void run(async () => { const result = await window.yibiao!.ppt.skills.identify({ repositoryUrl: url }); setRequest(result.repository || null); })}>请求管理端获取</button></div>
    {request && <p>请求 {request.requestId} · {request.status}<button disabled={busy} onClick={() => void run(async () => { const value = await window.yibiao!.ppt.skills.identify({ requestId: request.requestId }); if (value.candidateId) { setCandidate(value); setSelected(value.candidates.filter((item) => !item.missing?.length).map((item) => item.contentHash)); setRequest(null); } else setRequest(value.repository || request); })}>检查获取结果并识别</button></p>}
    {normalizePath && <section className="ppt-confirm-card"><h3>整理为个人技能</h3><p>原 Markdown 没有技能元数据。确认后仅为安装副本补充名称和用途，原文件保留。</p><input aria-label="技能标识" value={name} onChange={(event) => setName(event.target.value)} placeholder="英文标识，如 my-ppt-method" /><input aria-label="技能用途" value={description} onChange={(event) => setDescription(event.target.value)} placeholder="中文用途" /><button onClick={() => setNormalizePath('')}>取消</button><button disabled={busy || !name || !description.trim()} onClick={() => void run(async () => { const value = await window.yibiao!.ppt.skills.identify({ path: normalizePath, normalize: { name, description, confirmed: true } }); setCandidate(value); setSelected(value.candidates.filter((item) => !item.missing?.length).map((item) => item.contentHash)); setNormalizePath(''); })}>确认整理并检查</button></section>}
    {!items.length && <p className="ppt-empty">尚无个人安装技能。内置 ppt-master 在制作时单独校验，完整运行组件状态见项目。</p>}
    <button disabled={busy || !checked.length} onClick={() => { setRemoveReferenced(false); setRemove(items.filter((item) => checked.includes(item.contentHash))); }}>批量卸载所选技能</button>
    {items.map((item) => <article className="ppt-skill-item" key={item.contentHash}><label><input type="checkbox" aria-label={`选择 ${item.name}`} checked={checked.includes(item.contentHash)} onChange={(event) => setChecked(event.target.checked ? [...checked, item.contentHash] : checked.filter((hash) => hash !== item.contentHash))} /></label><div><strong>{item.name}</strong><span> {item.version}</span><p>{item.metadata?.description}</p><small>{item.status === 'retained' ? '项目固定版本仍保留；不供新项目选择' : item.status === 'ready' ? '固定工具兼容；实际任务仍需检查' : item.status === 'workflow_only' ? '方法参考可用；第三方脚本未获执行授权' : '缺资源或组件'}</small><p>{((item.metadata?.bytes || 0) / 1024 ** 2).toFixed(1)} MB · {item.metadata?.license}</p></div><label><input type="checkbox" checked={Boolean(item.enabled)} disabled={busy} onChange={(event) => void run(() => window.yibiao!.ppt.skills.enable({ contentHash: item.contentHash, enabled: event.target.checked }))} />{item.status === 'retained' ? '恢复启用' : '启用'}</label><button disabled={busy} onClick={() => { setRemoveReferenced(false); setRemove([item]); }}>卸载安装副本</button><details><summary>来源、权限与位置</summary><p>{item.metadata?.source}</p><p>{item.metadata?.permissions.join('；')}</p><code>{item.root}</code></details></article>)}
    {candidate && <section className="ppt-confirm-card"><h3>确认安装</h3>{candidate.candidates.map((item) => <p key={item.contentHash}><label><input type="checkbox" disabled={Boolean(item.missing?.length)} checked={selected.includes(item.contentHash)} onChange={(event) => setSelected(event.target.checked ? [...selected, item.contentHash] : selected.filter((hash) => hash !== item.contentHash))} /><strong>{item.name} · {item.version}</strong></label><br />{item.description}<br />来源：{item.source}<br />{item.license} · {((item.bytes || 0) / 1024 ** 2).toFixed(1)} MB<br />{item.permissions?.join('；')}{item.missing?.length ? `；缺少：${item.missing.join('、')}` : ''}</p>)}<div className="ppt-actions"><button disabled={busy} onClick={() => void run(discard)}>取消</button><button className="image-studio-primary" disabled={busy || !candidate.candidateId || !selected.length} onClick={() => void run(async () => { await window.yibiao!.ppt.skills.install({ candidateId: candidate.candidateId!, hashes: selected, confirmed: true }); setCandidate(null); })}>确认安装所选技能</button></div></section>}
    {remove && <section className="ppt-confirm-card"><h3>卸载 {remove.map((item) => item.name).join('、')}？</h3><p>仅删除个人安装副本，不删除原始文件或已导出 PPT。默认保留被项目锁定的版本，保留体积继续显示。</p>{storage?.projects.filter((project) => remove.some((item) => item.contentHash === project.contentHash)).map((project) => <p key={project.projectId}>受影响项目：{project.title}</p>)}<label><input type="checkbox" checked={removeReferenced} onChange={(event) => setRemoveReferenced(event.target.checked)} />连同项目固定版本删除；这些项目需要重新安装同一版本才能继续</label><div className="ppt-actions"><button onClick={() => setRemove(null)}>取消</button><button disabled={busy} onClick={() => void run(async () => { await window.yibiao!.ppt.skills.remove({ hashes: remove.map((item) => item.contentHash), confirmed: true, removeReferenced }); setRemove(null); setChecked([]); })}>确认卸载</button></div></section>}
  </Dialog.Content></Dialog.Portal></Dialog.Root>;
}
